# The only current way of using OS X virtual machines in Travis CI
# is setting up a generic environment
# This is not a problem because Python will be installed through conda

language: python
os: linux

branches:
  only:
    - master

env:
  global:
    - MPLBACKEND="Agg"

before_install:
  - apt install python3
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install --upgrade pip

install:
  - pip install black isort mypy --quiet

script:
  - . venv/bin/activate
  - isort -c -rc setup.py src/ -p einsteinpy -sd THIRDPARTY
  - black src/ setup.py --check
  - mypy --ignore-missing-imports --check-untyped-defs --no-strict-optional src/

sudo: false
