language: generic
os: osx

branches:
  only:
    - master

env:
  global:
    - MPLBACKEND="Agg"

before_install:
  - HOMEBREW_NO_AUTO_UPDATE=1 brew install python3
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install --upgrade pip

install:
  #- pip install numpy  # Required
  #- pip install .  # Test installation correctness
  #- pip install .[dev]  # Test development dependencies
  - pip install black --quiet

script:
  # - pytest -vv  # Test against installed code
  - black src/ setup.py --check

sudo: false
