version: 2
jobs:
  quality:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install black isort mypy --quiet
      - run:
          name: check Black style
          command: |
            . venv/bin/activate
            isort -c -rc setup.py src/ -p einsteinpy -sd THIRDPARTY  # This avoids installing einsteinpy
            black src/ setup.py --check
      - run:
          name: check MyPy
          command: |
            . venv/bin/activate
            mypy --ignore-missing-imports --check-untyped-defs --no-strict-optional src/

workflows:
  version: 2
  build_and_test:
    jobs:
      - quality
